name = "OptimalBranchingSTN"
uuid = "7c04d9f1-680d-4e5e-814a-5309a9885dea"
authors = ["XuanzhaoGao <arrogantgao@outlook.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
