name = "OptimalBranchingSTN"
uuid = "7c04d9f1-680d-4e5e-814a-5309a9885dea"
authors = ["XuanzhaoGao <arrogantgao@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
GenericTensorNetworks = "3521c873-ad32-4bb4-b63d-f4f178f42b49"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
OptimalBranchingCore = "c76e7b22-e1d2-40e8-b0f1-f659837787b8"

[compat]
GenericTensorNetworks = "3.2.0"
OMEinsum = "0.8.4"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
